export const speciesList = [
  { "name": "Ashwagandha", "speciesId": "ASW2025" },
  { "name": "Mulethi (Licorice Root)", "speciesId": "MUL2025" },
  { "name": "Tulsi (Holy Basil)", "speciesId": "TUL2025" },
  { "name": "Amla (Indian Gooseberry)", "speciesId": "AML2025" },
  { "name": "Brahmi", "speciesId": "BRA2025" },
  { "name": "Shatavari", "speciesId": "SHA2025" },
  { "name": "Giloy (Guduchi)", "speciesId": "GIL2025" },
  { "name": "Neem", "speciesId": "NEE2025" },
  { "name": "Turmeric (Haldi)", "speciesId": "TUR2025" },
  { "name": "Manjistha", "speciesId": "MAN2025" },
  { "name": "Haritaki", "speciesId": "HAR2025" },
  { "name": "Bibhitaki", "speciesId": "BIB2025" },
  { "name": "Triphala", "speciesId": "TRI2025" },
  { "name": "Arjuna Bark", "speciesId": "ARJ2025" },
  { "name": "Bhringraj", "speciesId": "BHR2025" },
  { "name": "Punarnava", "speciesId": "PUN2025" },
  { "name": "Gokshura (Tribulus terrestris)", "speciesId": "GOK2025" },
  { "name": "Kutki", "speciesId": "KUT2025" },
  { "name": "Vacha (Sweet Flag)", "speciesId": "VAC2025" },
  { "name": "Jatamansi", "speciesId": "JAT2025" },
  { "name": "Kalmegh (Andrographis)", "speciesId": "KAL2025" },
  { "name": "Shankhpushpi", "speciesId": "SHAK2025" },
  { "name": "Pippali (Long Pepper)", "speciesId": "PIP2025" },
  { "name": "Guggul", "speciesId": "GUG2025" },
  { "name": "Trikatu", "speciesId": "TRK2025" },
  { "name": "Chitrak", "speciesId": "CHI2025" },
  { "name": "Tagar (Valerian Root)", "speciesId": "TAG2025" },
  { "name": "Lodhra", "speciesId": "LOD2025" },
  { "name": "Safed Musli", "speciesId": "SAF2025" },
  { "name": "Vidanga", "speciesId": "VID2025" },
  { "name": "Nagarmotha (Nut Grass)", "speciesId": "NAG2025" },
  { "name": "Anantmool (Indian Sarsaparilla)", "speciesId": "ANA2025" },
  { "name": "Shilajit", "speciesId": "SHI2025" },
  { "name": "Sariva", "speciesId": "SAR2025" },
  { "name": "Ajwain", "speciesId": "AJW2025" },
  { "name": "Jeera (Cumin)", "speciesId": "JEE2025" },
  { "name": "Dhania (Coriander)", "speciesId": "DHA2025" },
  { "name": "Saunf (Fennel)", "speciesId": "SAU2025" },
  { "name": "Hing (Asafoetida)", "speciesId": "HIN2025" },
  { "name": "Methika (Fenugreek)", "speciesId": "MET2025" },
  { "name": "Bala (Sida cordifolia)", "speciesId": "BAL2025" },
  { "name": "Atibala", "speciesId": "ATI2025" },
  { "name": "Rasna", "speciesId": "RAS2025" },
  { "name": "Devdaru (Himalayan Cedar)", "speciesId": "DEV2025" },
  { "name": "Bakuchi", "speciesId": "BAK2025" },
  { "name": "Agnimantha", "speciesId": "AGN2025" },
  { "name": "Patha", "speciesId": "PAT2025" },
  { "name": "Kantakari", "speciesId": "KAN2025" },
  { "name": "Vasaka (Adhatoda vasica)", "speciesId": "VAS2025" },
  { "name": "Talispatra", "speciesId": "TAL2025" },
  { "name": "Mustaka (Nut Grass)", "speciesId": "MUS2025" },
  { "name": "Karela (Bitter Gourd)", "speciesId": "KAR2025" },
  { "name": "Gudmar (Gymnema sylvestre)", "speciesId": "GUD2025" },
  { "name": "Moringa (Drumstick Tree)", "speciesId": "MOR2025" }
]
